version: '2'
services:
  factorio:
    container_name: 'factorio-server'
    hostname: 'factorio-server'
    image: 'local/factorio-server:latest'
    ports:
     - "34197:34197/udp"
     - "27015:27015/tcp"
    volumes:
     - ~/factorio/volume:/factorio
    environment:
      - PUID=1000
      - PGID=1000
      - UPDATE_MODS_ON_START=true
      